[package]
name = "armstrong"
version = "0.0.1"
authors = ["mikael@silven.nu"]

[lib]
name = "armstrong"
crate-type = ["lib"]

[profile.release]
lto = true
panic = 'abort'

[target.thumbv7m-none-eabi.dependencies]
cortex-m = "^0.2"
cortex-m-rt = "^0.2"
